<a href="https://colab.research.google.com/github/HurtaClaudio/DeepLearningSpecialization/blob/main/Colab_2_Introducci%C3%B3n_a_TensorFlow_2_0_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/joanby/tensorflow2/blob/master/Colab%202%20-%20Introducción%20a%20TensorFlow%202.0%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TensorFlow 1.X

### Instalar TensorFlow 1.X



## Especificando la versión de TensorFlow

Ejecutando "importar tensorflow" importará la versión por defecto (actualmente 2.x). Puedes usar la 1.x ejecutando una celda con la "versión mágica de tensorflow" **antes de ejecutar "importar tensorflow".

### Si no funciona hacer el pip install



In [6]:
!pip install tensorflow==1.13.1
%tensorflow_version 1.x

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


ValueError: ignored

In [7]:
import tensorflow as tf

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or 

In [8]:
tf.__version__

'1.13.1'

### Constantes

#### Definir una constante

In [9]:
# Definir una constante en TensorFlow
tensor = tf.constant([[23, 4], [32, 51]])

In [10]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [11]:
# Si la session no ha sido inicializada, no se pueden acceder a los valores de la constante
tensor.eval()

ValueError: ignored

#### Consultar los valores de la constante

In [13]:
session = tf.Session()

In [14]:
session.run(tf.global_variables_initializer())
#session.run(tf.global_variables_initializer())

In [15]:
tensor_value = session.run(tensor)
#tensor_value = session.run(tensor)

In [16]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

### Variables

#### Definir una variable

In [17]:
# Definir una variable de TensorFlow 
variable = tf.Variable([[30, 20], [10, 45]])

Instructions for updating:
Colocations handled automatically by placer.


In [18]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [19]:
# Si la session no ha sido inicializada, no se podrán acceder a los valores de la variable
variable.eval()

ValueError: ignored

#### Consultar los valores de una variable

In [20]:
# Inicializar una session
session = tf.Session()

In [21]:
# Inicializar TODAS las variables de la session
session.run(tf.global_variables_initializer())

In [22]:
# Ejecutar el método eval en el entorno con la sesión iniciada para recuperar los valores del mismo
variable.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

## TensorFlow 2.0

### Instalar TensorFlow 2.0

In [30]:
!pip uninstall tensorflow

Found existing installation: tensorflow 1.13.1
Uninstalling tensorflow-1.13.1:
  Would remove:
    /usr/local/bin/freeze_graph
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.7/dist-packages/tensorflow-1.13.1.dist-info/*
    /usr/local/lib/python3.7/dist-packages/tensorflow/*
Proceed (y/n)?   ERROR: Operation cancelled by user


In [1]:
!y

/bin/bash: y: command not found


In [4]:
!pip install tensorflow-gpu==2.0.0-alpha0
%tensorflow_version 2.x

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==2.0.0-alpha0 (from versions: 1.13.1, 1.13.2, 1.14.0, 1.15.0, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2)
ERROR: No matching distribution found for tensorflow-gpu==2.0.0-alpha0
Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [5]:
import tensorflow as tf
import numpy as np

In [6]:
tf.__version__

'2.9.2'

### Constantes

#### Definir una constante

In [7]:
# Definir una constante en TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])
#tensor_20 = tf.constant([[23, 4], [32, 51]])

In [8]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [9]:
# Obtener el tamaño de un tensor
tensor_20.shape

TensorShape([2, 2])

#### Consultar los valores de una constante

In [10]:
# Obtener los valores directamente desde una constante de TensorFlow con numpy, sin necesidad de una session
tensor_20.numpy()
#tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [11]:
# Podemos convertir un array de numpy a un tensor de TensorFlow directamente
numpy_tensor = np.array([[23, 4], [32, 51]])
#numpy_tensor = np.array([[23,  4], [32, 51]])

In [12]:
tensor_from_numpy = tf.constant(numpy_tensor)
#tensor_from_numpy = tf.constant(numpy_tensor)

In [13]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Variables

#### Definir una variable

In [19]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Consultar los valores de una variable

In [20]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Cambiar un valor especifico de una variable

In [21]:
tf2_variable[0,2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [22]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operaciones con tensores

In [23]:
tensor = tf.constant([[1,2], [3,4]])
#tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Sumar un escalar a un tensor

In [24]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplicar un escalar por un tensor

In [25]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Utilizar funciones de Numpy sobre tensores de TensorFlow

In [27]:
# Obtener los cuadrados de todos los números de un tensor de TensorFlow
np.square(tensor)
#np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [28]:
# Obtener la raíz cuadrada de todos los números de un tensor de TensorFlow
np.sqrt(tensor)
#np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Producto escalar entre dos tensores

In [29]:
print(tensor)
print(tensor_20)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[23  4]
 [32 51]], shape=(2, 2), dtype=int32)


In [30]:
#no.dot se refiere a la multiplicacion de matrices.
np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Strings en TensorFlow 2.0

In [38]:
tf_string = tf.constant('TensorFlow')
#tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

#### Operaciones simples con strings

In [34]:
tf.strings.length(tf_string).numpy()
#tf.strings.length(tf_string)

10

In [40]:
tf.strings.unicode_decode(tf_string, 'utf8')
#tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

#### Almacenar arrays de strings

In [41]:
tf_string_array = tf.constant(['TensorFlow', 'Deep Learning', 'AI'])
#tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])
tf.strings.length(tf_string_array)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 13,  2], dtype=int32)>

In [ ]:
# Iterar sobre un array de strings en TF
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)


In [42]:
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
